### ISSUE TITLE
Lib doesn't work with Raspberry Pi 4B

### ISSUE THREAD

**Issue by houserockr** [adafruit/Adafruit_CircuitPython_WS2801#16]
I can operate a ws2801 led strip with the old/deprecated python2 adafruit_ws2801 lib.
my pin assignment:
```
5V  => 04 (+5)
CK  => 23 (SCLK)
SI  => 19 (MOSI)
GND => 06 (GND)
```

a `pprint(board)` shows me the following dict:

`'pin': <module 'adafruit_blinka.microcontroller.bcm283x.pin' from '/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/bcm283x/pin.py'>, 'D0': 0, 'D1': 1, 'D2': 2, 'SDA': 2, 'D3': 3, 'SCL': 3, 'D4': 4, 'D5': 5, 'D6': 6, 'D7': 7, 'CE1': 7, 'D8': 8, 'CE0': 8, 'D9': 9, 'MISO': 9, 'D10': 10, 'MOSI': 10, 'D11': 11, 'SCLK': 11, 'SCK': 11, 'D12': 12, 'D13': 13, 'D14': 14, 'TXD': 14, 'D15': 15, 'RXD': 15, 'TX': 14, 'RX': 15, 'D16': 16, 'D17': 17, 'D18': 18, 'D19': 19, 'MISO_1': 19, 'D20': 20, 'MOSI_1': 20, 'D21': 21, 'SCLK_1': 21, 'SCK_1': 21, 'D22': 22, 'D23': 23, 'D24': 24, 'D25': 25, 'D26': 26, 'D27': 27, 'I2C': <function I2C at 0xb667f738>, 'SPI': <function SPI at 0xb65fc030>}`

which doesn't match the pin layout of the 4B model at all.
For instance, on the 4B
MOSI is 19 and SCLK is 23

see https://pinout.xyz/

Is there any way to configure/setup the lib by using the constructor differently?

**Comment by kattni** [comment]
@makermelissa Can you take a look at this? Thanks!

**Comment by houserockr** [comment]
Sorry that I didn't come back, but it finally worked. Turns out I specified the wrong amount of LEDs. I had 14 physical LEDs, but only specified 7 in the constructor.

Here's how I call the constructor:

```
import board
import adafruit_ws2801
...
self.leds = adafruit_ws2801.WS2801(board.SCLK, board.MOSI, 14)
```

Kind of funny though that it works, because the port mapping mentioned above actually does not match the numbers of my RPi 4B board.

**Comment by makermelissa** [comment]
@houserockr awesome that it works. The pin numbers don't correspond to the physical pin numbers, but rather the Broadcom Pin numbers (See https://pinout.xyz/ for example). Closing since it's working.
