### ISSUE TITLE
Library Compatability with NVIDIA Jetson series

### ISSUE THREAD

**Issue by dongsin-kim** [adafruit/Adafruit_CircuitPython_WS2801#17]
Hi all,

I just have some questions with this repository. :-)

Q1.
I am just wondering that is this repository compatible with the hardware (**NVIDIA Jetson** series)?

Q2.
Could you please explain me that what is the difference between this repository and [the Blinka repository](https://github.com/adafruit/Adafruit_Blinka)?

**Comment by ladyada** [comment]
we  have not tested it, probably works
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux

**Comment by dongsin-kim** [comment]
Thank you for the supports. I have tested the library and it works on NVIDIA Jetson Nano. :-)

What I have been done is the same as this link (except for the device):
https://tutorials-raspberrypi.com/how-to-control-a-raspberry-pi-ws2801-rgb-led-strip/
